services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile_frontend
      target: frontend
      args:
        - DOCKERHUB_USERNAME
    image: '$DOCKERHUB_USERNAME/quirknotes_frontend:latest'
    ports:
      - "3000:3000"
    environment:
      - ENV=Docker

  backend:
    build:
      context: .
      dockerfile: Dockerfile_backend
      target: backend
      args:
        - DOCKERHUB_USERNAME
    image: '$DOCKERHUB_USERNAME/quirknotes_backend:latest'
    ports:
      - "4000:4000"
    environment:
      - ENV=Docker
    depends_on:
      - mongodb

  mongodb:
    image: mongo:latest
    ports:
     - "27017:27017"